/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author neelam
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /** Creates new form CalculatorGUI */
    public CalculatorGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        piButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        modButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        mulButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        closeBracketButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        openBracketButton = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        powButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        valueOfExpressionLabel = new javax.swing.JLabel();
        expressionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.title")); // NOI18N
        setBackground(new java.awt.Color(245, 185, 125));
        setName("CalculatorFrame"); // NOI18N

        headingLabel.setFont(new java.awt.Font("Serif", 1, 25)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(headingLabel, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.headingLabel.text")); // NOI18N

        oneButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(oneButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.oneButton.text")); // NOI18N

        twoButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(twoButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.twoButton.text")); // NOI18N

        threeButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(threeButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.threeButton.text")); // NOI18N

        addButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(addButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.addButton.text")); // NOI18N

        sinButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(sinButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.sinButton.text")); // NOI18N

        piButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(piButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.piButton.text")); // NOI18N

        fourButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(fourButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.fourButton.text")); // NOI18N

        fiveButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(fiveButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.fiveButton.text")); // NOI18N

        sixButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(sixButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.sixButton.text")); // NOI18N

        subButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(subButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.subButton.text")); // NOI18N

        cosButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(cosButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.cosButton.text")); // NOI18N

        modButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(modButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.modButton.text")); // NOI18N

        sqrtButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(sqrtButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.sqrtButton.text")); // NOI18N

        tanButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(tanButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.tanButton.text")); // NOI18N

        mulButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mulButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.mulButton.text")); // NOI18N

        nineButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nineButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.nineButton.text")); // NOI18N

        eightButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(eightButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.eightButton.text")); // NOI18N

        sevenButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(sevenButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.sevenButton.text")); // NOI18N

        equalButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(equalButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.equalButton.text")); // NOI18N

        decimalButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(decimalButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.decimalButton.text")); // NOI18N

        divButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(divButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.divButton.text")); // NOI18N

        closeBracketButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(closeBracketButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.closeBracketButton.text")); // NOI18N

        zeroButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(zeroButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.zeroButton.text")); // NOI18N

        openBracketButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(openBracketButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.openBracketButton.text")); // NOI18N

        commaButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(commaButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.commaButton.text")); // NOI18N

        powButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(powButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.powButton.text")); // NOI18N

        deleteButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(deleteButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.deleteButton.text")); // NOI18N

        eButton.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(eButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.eButton.text")); // NOI18N
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(clearButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.clearButton.text")); // NOI18N

        logButton.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(logButton, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.logButton.text")); // NOI18N

        valueOfExpressionLabel.setForeground(new java.awt.Color(239, 237, 237));
        org.openide.awt.Mnemonics.setLocalizedText(valueOfExpressionLabel, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.valueOfExpressionLabel.text")); // NOI18N
        valueOfExpressionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        expressionLabel.setForeground(new java.awt.Color(255, 233, 233));
        org.openide.awt.Mnemonics.setLocalizedText(expressionLabel, org.openide.util.NbBundle.getMessage(CalculatorGUI.class, "CalculatorGUI.expressionLabel.text")); // NOI18N
        expressionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(headingLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(modButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(openBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(closeBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(valueOfExpressionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(expressionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expressionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(valueOfExpressionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closeBracketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(commaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeBracketButton;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JLabel expressionLabel;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton logButton;
    private javax.swing.JButton modButton;
    private javax.swing.JButton mulButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton openBracketButton;
    private javax.swing.JButton piButton;
    private javax.swing.JButton powButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton subButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JLabel valueOfExpressionLabel;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables

}
